---
- name: restarting the required services
  service:
    name: "{{item}}"
    state: restarted
  with_items:
  - httpd
  - nginx
  - postgresql
  - php5-fpm
  - postfix
  - openvpn
  - unbound
  - monit
  failed_when: false